/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthenticatedBalancoFiscalRouteImport } from './routes/_authenticated/balanco-fiscal'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedClientesObrasRouteImport } from './routes/_authenticated/clientes-obras'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContasPagarRouteImport } from './routes/_authenticated/contas-pagar'
import { Route as AuthenticatedContasReceberRouteImport } from './routes/_authenticated/contas-receber'
import { Route as AuthenticatedCotacoesRouteImport } from './routes/_authenticated/cotacoes'
import { Route as AuthenticatedCreditoRouteImport } from './routes/_authenticated/credito'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEstoqueMovimentosRouteImport } from './routes/_authenticated/estoque-movimentos'
import { Route as AuthenticatedFilialExtraRouteImport } from './routes/_authenticated/filial-extra'
import { Route as AuthenticatedFiscalRouteImport } from './routes/_authenticated/fiscal'
import { Route as AuthenticatedFluxoCaixaRouteImport } from './routes/_authenticated/fluxo-caixa'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedGiroEstoqueRouteImport } from './routes/_authenticated/giro-estoque'
import { Route as AuthenticatedInventariosRouteImport } from './routes/_authenticated/inventarios'
import { Route as AuthenticatedLucroRouteImport } from './routes/_authenticated/lucro'
import { Route as AuthenticatedMotoristaRouteImport } from './routes/_authenticated/motorista'
import { Route as AuthenticatedMotoristasRouteImport } from './routes/_authenticated/motoristas'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedNfeRouteImport } from './routes/_authenticated/nfe'
import { Route as AuthenticatedObrasRouteImport } from './routes/_authenticated/obras'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedPainelFilialRouteImport } from './routes/_authenticated/painel-filial'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPrecosRouteImport } from './routes/_authenticated/precos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated/profissionais'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedRotaRouteImport } from './routes/_authenticated/rota'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedComprasIndexRouteImport } from './routes/_authenticated/compras.index'
import { Route as AuthenticatedComprasIdRouteImport } from './routes/_authenticated/compras.$id'
import { Route as AuthenticatedDepositosIndexRouteImport } from './routes/_authenticated/depositos.index'
import { Route as AuthenticatedDepositosIdRouteImport } from './routes/_authenticated/depositos.$id'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBalancoFiscalRoute =
  AuthenticatedBalancoFiscalRouteImport.update({
    id: '/balanco-fiscal',
    path: '/balanco-fiscal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesObrasRoute =
  AuthenticatedClientesObrasRouteImport.update({
    id: '/clientes-obras',
    path: '/clientes-obras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasPagarRoute =
  AuthenticatedContasPagarRouteImport.update({
    id: '/contas-pagar',
    path: '/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasReceberRoute =
  AuthenticatedContasReceberRouteImport.update({
    id: '/contas-receber',
    path: '/contas-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCotacoesRoute = AuthenticatedCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditoRoute = AuthenticatedCreditoRouteImport.update({
  id: '/credito',
  path: '/credito',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueMovimentosRoute =
  AuthenticatedEstoqueMovimentosRouteImport.update({
    id: '/estoque-movimentos',
    path: '/estoque-movimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilialExtraRoute =
  AuthenticatedFilialExtraRouteImport.update({
    id: '/filial-extra',
    path: '/filial-extra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFiscalRoute = AuthenticatedFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluxoCaixaRoute = AuthenticatedFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGiroEstoqueRoute =
  AuthenticatedGiroEstoqueRouteImport.update({
    id: '/giro-estoque',
    path: '/giro-estoque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventariosRoute =
  AuthenticatedInventariosRouteImport.update({
    id: '/inventarios',
    path: '/inventarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLucroRoute = AuthenticatedLucroRouteImport.update({
  id: '/lucro',
  path: '/lucro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristaRoute = AuthenticatedMotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristasRoute = AuthenticatedMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNfeRoute = AuthenticatedNfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasRoute = AuthenticatedObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelFilialRoute =
  AuthenticatedPainelFilialRouteImport.update({
    id: '/painel-filial',
    path: '/painel-filial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecosRoute = AuthenticatedPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotaRoute = AuthenticatedRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasIndexRoute =
  AuthenticatedComprasIndexRouteImport.update({
    id: '/compras/',
    path: '/compras/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasIdRoute = AuthenticatedComprasIdRouteImport.update({
  id: '/compras/$id',
  path: '/compras/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositosIndexRoute =
  AuthenticatedDepositosIndexRouteImport.update({
    id: '/depositos/',
    path: '/depositos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositosIdRoute =
  AuthenticatedDepositosIdRouteImport.update({
    id: '/depositos/$id',
    path: '/depositos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/balanco-fiscal': typeof AuthenticatedBalancoFiscalRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/clientes-obras': typeof AuthenticatedClientesObrasRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/cotacoes': typeof AuthenticatedCotacoesRoute
  '/credito': typeof AuthenticatedCreditoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/estoque-movimentos': typeof AuthenticatedEstoqueMovimentosRoute
  '/filial-extra': typeof AuthenticatedFilialExtraRoute
  '/fiscal': typeof AuthenticatedFiscalRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/giro-estoque': typeof AuthenticatedGiroEstoqueRoute
  '/inventarios': typeof AuthenticatedInventariosRoute
  '/lucro': typeof AuthenticatedLucroRoute
  '/motorista': typeof AuthenticatedMotoristaRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/painel-filial': typeof AuthenticatedPainelFilialRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/compras/$id': typeof AuthenticatedComprasIdRoute
  '/depositos/$id': typeof AuthenticatedDepositosIdRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/compras/': typeof AuthenticatedComprasIndexRoute
  '/depositos/': typeof AuthenticatedDepositosIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/balanco-fiscal': typeof AuthenticatedBalancoFiscalRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/clientes-obras': typeof AuthenticatedClientesObrasRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/cotacoes': typeof AuthenticatedCotacoesRoute
  '/credito': typeof AuthenticatedCreditoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/estoque-movimentos': typeof AuthenticatedEstoqueMovimentosRoute
  '/filial-extra': typeof AuthenticatedFilialExtraRoute
  '/fiscal': typeof AuthenticatedFiscalRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/giro-estoque': typeof AuthenticatedGiroEstoqueRoute
  '/inventarios': typeof AuthenticatedInventariosRoute
  '/lucro': typeof AuthenticatedLucroRoute
  '/motorista': typeof AuthenticatedMotoristaRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/painel-filial': typeof AuthenticatedPainelFilialRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/compras/$id': typeof AuthenticatedComprasIdRoute
  '/depositos/$id': typeof AuthenticatedDepositosIdRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/compras': typeof AuthenticatedComprasIndexRoute
  '/depositos': typeof AuthenticatedDepositosIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/_authenticated/balanco-fiscal': typeof AuthenticatedBalancoFiscalRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/clientes-obras': typeof AuthenticatedClientesObrasRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/_authenticated/contas-receber': typeof AuthenticatedContasReceberRoute
  '/_authenticated/cotacoes': typeof AuthenticatedCotacoesRoute
  '/_authenticated/credito': typeof AuthenticatedCreditoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/estoque-movimentos': typeof AuthenticatedEstoqueMovimentosRoute
  '/_authenticated/filial-extra': typeof AuthenticatedFilialExtraRoute
  '/_authenticated/fiscal': typeof AuthenticatedFiscalRoute
  '/_authenticated/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/giro-estoque': typeof AuthenticatedGiroEstoqueRoute
  '/_authenticated/inventarios': typeof AuthenticatedInventariosRoute
  '/_authenticated/lucro': typeof AuthenticatedLucroRoute
  '/_authenticated/motorista': typeof AuthenticatedMotoristaRoute
  '/_authenticated/motoristas': typeof AuthenticatedMotoristasRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/nfe': typeof AuthenticatedNfeRoute
  '/_authenticated/obras': typeof AuthenticatedObrasRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/painel-filial': typeof AuthenticatedPainelFilialRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/precos': typeof AuthenticatedPrecosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/rota': typeof AuthenticatedRotaRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/_authenticated/compras/$id': typeof AuthenticatedComprasIdRoute
  '/_authenticated/depositos/$id': typeof AuthenticatedDepositosIdRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/compras/': typeof AuthenticatedComprasIndexRoute
  '/_authenticated/depositos/': typeof AuthenticatedDepositosIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/balanco-fiscal'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/clientes-obras'
    | '/comissoes'
    | '/configuracoes'
    | '/contas-pagar'
    | '/contas-receber'
    | '/cotacoes'
    | '/credito'
    | '/dashboard'
    | '/entregas'
    | '/estoque'
    | '/estoque-movimentos'
    | '/filial-extra'
    | '/fiscal'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/giro-estoque'
    | '/inventarios'
    | '/lucro'
    | '/motorista'
    | '/motoristas'
    | '/movimentacoes'
    | '/nfe'
    | '/obras'
    | '/orcamentos'
    | '/painel-filial'
    | '/pdv'
    | '/planos'
    | '/precos'
    | '/produtos'
    | '/profissionais'
    | '/relatorio'
    | '/rota'
    | '/usuarios'
    | '/veiculos'
    | '/compras/$id'
    | '/depositos/$id'
    | '/pedidos/$id'
    | '/compras/'
    | '/depositos/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/balanco-fiscal'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/clientes-obras'
    | '/comissoes'
    | '/configuracoes'
    | '/contas-pagar'
    | '/contas-receber'
    | '/cotacoes'
    | '/credito'
    | '/dashboard'
    | '/entregas'
    | '/estoque'
    | '/estoque-movimentos'
    | '/filial-extra'
    | '/fiscal'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/giro-estoque'
    | '/inventarios'
    | '/lucro'
    | '/motorista'
    | '/motoristas'
    | '/movimentacoes'
    | '/nfe'
    | '/obras'
    | '/orcamentos'
    | '/painel-filial'
    | '/pdv'
    | '/planos'
    | '/precos'
    | '/produtos'
    | '/profissionais'
    | '/relatorio'
    | '/rota'
    | '/usuarios'
    | '/veiculos'
    | '/compras/$id'
    | '/depositos/$id'
    | '/pedidos/$id'
    | '/compras'
    | '/depositos'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/_authenticated/balanco-fiscal'
    | '/_authenticated/caixa'
    | '/_authenticated/categorias'
    | '/_authenticated/clientes'
    | '/_authenticated/clientes-obras'
    | '/_authenticated/comissoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas-pagar'
    | '/_authenticated/contas-receber'
    | '/_authenticated/cotacoes'
    | '/_authenticated/credito'
    | '/_authenticated/dashboard'
    | '/_authenticated/entregas'
    | '/_authenticated/estoque'
    | '/_authenticated/estoque-movimentos'
    | '/_authenticated/filial-extra'
    | '/_authenticated/fiscal'
    | '/_authenticated/fluxo-caixa'
    | '/_authenticated/fornecedores'
    | '/_authenticated/giro-estoque'
    | '/_authenticated/inventarios'
    | '/_authenticated/lucro'
    | '/_authenticated/motorista'
    | '/_authenticated/motoristas'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/nfe'
    | '/_authenticated/obras'
    | '/_authenticated/orcamentos'
    | '/_authenticated/painel-filial'
    | '/_authenticated/pdv'
    | '/_authenticated/planos'
    | '/_authenticated/precos'
    | '/_authenticated/produtos'
    | '/_authenticated/profissionais'
    | '/_authenticated/relatorio'
    | '/_authenticated/rota'
    | '/_authenticated/usuarios'
    | '/_authenticated/veiculos'
    | '/_authenticated/compras/$id'
    | '/_authenticated/depositos/$id'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/compras/'
    | '/_authenticated/depositos/'
    | '/_authenticated/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/balanco-fiscal': {
      id: '/_authenticated/balanco-fiscal'
      path: '/balanco-fiscal'
      fullPath: '/balanco-fiscal'
      preLoaderRoute: typeof AuthenticatedBalancoFiscalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes-obras': {
      id: '/_authenticated/clientes-obras'
      path: '/clientes-obras'
      fullPath: '/clientes-obras'
      preLoaderRoute: typeof AuthenticatedClientesObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-pagar': {
      id: '/_authenticated/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/contas-pagar'
      preLoaderRoute: typeof AuthenticatedContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-receber': {
      id: '/_authenticated/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AuthenticatedContasReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes': {
      id: '/_authenticated/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof AuthenticatedCotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credito': {
      id: '/_authenticated/credito'
      path: '/credito'
      fullPath: '/credito'
      preLoaderRoute: typeof AuthenticatedCreditoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque-movimentos': {
      id: '/_authenticated/estoque-movimentos'
      path: '/estoque-movimentos'
      fullPath: '/estoque-movimentos'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filial-extra': {
      id: '/_authenticated/filial-extra'
      path: '/filial-extra'
      fullPath: '/filial-extra'
      preLoaderRoute: typeof AuthenticatedFilialExtraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiscal': {
      id: '/_authenticated/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof AuthenticatedFiscalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo-caixa': {
      id: '/_authenticated/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/giro-estoque': {
      id: '/_authenticated/giro-estoque'
      path: '/giro-estoque'
      fullPath: '/giro-estoque'
      preLoaderRoute: typeof AuthenticatedGiroEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventarios': {
      id: '/_authenticated/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof AuthenticatedInventariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lucro': {
      id: '/_authenticated/lucro'
      path: '/lucro'
      fullPath: '/lucro'
      preLoaderRoute: typeof AuthenticatedLucroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorista': {
      id: '/_authenticated/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof AuthenticatedMotoristaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motoristas': {
      id: '/_authenticated/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof AuthenticatedMotoristasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfe': {
      id: '/_authenticated/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof AuthenticatedNfeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras': {
      id: '/_authenticated/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AuthenticatedObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-filial': {
      id: '/_authenticated/painel-filial'
      path: '/painel-filial'
      fullPath: '/painel-filial'
      preLoaderRoute: typeof AuthenticatedPainelFilialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precos': {
      id: '/_authenticated/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof AuthenticatedPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota': {
      id: '/_authenticated/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AuthenticatedRotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras/': {
      id: '/_authenticated/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof AuthenticatedComprasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras/$id': {
      id: '/_authenticated/compras/$id'
      path: '/compras/$id'
      fullPath: '/compras/$id'
      preLoaderRoute: typeof AuthenticatedComprasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depositos/': {
      id: '/_authenticated/depositos/'
      path: '/depositos'
      fullPath: '/depositos/'
      preLoaderRoute: typeof AuthenticatedDepositosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depositos/$id': {
      id: '/_authenticated/depositos/$id'
      path: '/depositos/$id'
      fullPath: '/depositos/$id'
      preLoaderRoute: typeof AuthenticatedDepositosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBalancoFiscalRoute: typeof AuthenticatedBalancoFiscalRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedClientesObrasRoute: typeof AuthenticatedClientesObrasRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasPagarRoute: typeof AuthenticatedContasPagarRoute
  AuthenticatedContasReceberRoute: typeof AuthenticatedContasReceberRoute
  AuthenticatedCotacoesRoute: typeof AuthenticatedCotacoesRoute
  AuthenticatedCreditoRoute: typeof AuthenticatedCreditoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedEstoqueMovimentosRoute: typeof AuthenticatedEstoqueMovimentosRoute
  AuthenticatedFilialExtraRoute: typeof AuthenticatedFilialExtraRoute
  AuthenticatedFiscalRoute: typeof AuthenticatedFiscalRoute
  AuthenticatedFluxoCaixaRoute: typeof AuthenticatedFluxoCaixaRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedGiroEstoqueRoute: typeof AuthenticatedGiroEstoqueRoute
  AuthenticatedInventariosRoute: typeof AuthenticatedInventariosRoute
  AuthenticatedLucroRoute: typeof AuthenticatedLucroRoute
  AuthenticatedMotoristaRoute: typeof AuthenticatedMotoristaRoute
  AuthenticatedMotoristasRoute: typeof AuthenticatedMotoristasRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedNfeRoute: typeof AuthenticatedNfeRoute
  AuthenticatedObrasRoute: typeof AuthenticatedObrasRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPainelFilialRoute: typeof AuthenticatedPainelFilialRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPrecosRoute: typeof AuthenticatedPrecosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedRotaRoute: typeof AuthenticatedRotaRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedComprasIdRoute: typeof AuthenticatedComprasIdRoute
  AuthenticatedDepositosIdRoute: typeof AuthenticatedDepositosIdRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedComprasIndexRoute: typeof AuthenticatedComprasIndexRoute
  AuthenticatedDepositosIndexRoute: typeof AuthenticatedDepositosIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBalancoFiscalRoute: AuthenticatedBalancoFiscalRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedClientesObrasRoute: AuthenticatedClientesObrasRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContasPagarRoute: AuthenticatedContasPagarRoute,
  AuthenticatedContasReceberRoute: AuthenticatedContasReceberRoute,
  AuthenticatedCotacoesRoute: AuthenticatedCotacoesRoute,
  AuthenticatedCreditoRoute: AuthenticatedCreditoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedEstoqueMovimentosRoute: AuthenticatedEstoqueMovimentosRoute,
  AuthenticatedFilialExtraRoute: AuthenticatedFilialExtraRoute,
  AuthenticatedFiscalRoute: AuthenticatedFiscalRoute,
  AuthenticatedFluxoCaixaRoute: AuthenticatedFluxoCaixaRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedGiroEstoqueRoute: AuthenticatedGiroEstoqueRoute,
  AuthenticatedInventariosRoute: AuthenticatedInventariosRoute,
  AuthenticatedLucroRoute: AuthenticatedLucroRoute,
  AuthenticatedMotoristaRoute: AuthenticatedMotoristaRoute,
  AuthenticatedMotoristasRoute: AuthenticatedMotoristasRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedNfeRoute: AuthenticatedNfeRoute,
  AuthenticatedObrasRoute: AuthenticatedObrasRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPainelFilialRoute: AuthenticatedPainelFilialRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPrecosRoute: AuthenticatedPrecosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedRotaRoute: AuthenticatedRotaRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedComprasIdRoute: AuthenticatedComprasIdRoute,
  AuthenticatedDepositosIdRoute: AuthenticatedDepositosIdRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedComprasIndexRoute: AuthenticatedComprasIndexRoute,
  AuthenticatedDepositosIndexRoute: AuthenticatedDepositosIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
