/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ZeTechLoginRouteImport } from './routes/ze-tech-login'
import { Route as AuthenticatedBalancoFiscalRouteImport } from './routes/_authenticated/balanco-fiscal'
import { Route as AuthenticatedBancoMovimentosRouteImport } from './routes/_authenticated/banco-movimentos'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedClientesObrasRouteImport } from './routes/_authenticated/clientes-obras'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContasBancariasRouteImport } from './routes/_authenticated/contas-bancarias'
import { Route as AuthenticatedContasPagarRouteImport } from './routes/_authenticated/contas-pagar'
import { Route as AuthenticatedContasReceberRouteImport } from './routes/_authenticated/contas-receber'
import { Route as AuthenticatedCotacoesRouteImport } from './routes/_authenticated/cotacoes'
import { Route as AuthenticatedCreditoRouteImport } from './routes/_authenticated/credito'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEstoqueMovimentosRouteImport } from './routes/_authenticated/estoque-movimentos'
import { Route as AuthenticatedExtratoReceberRouteImport } from './routes/_authenticated/extrato-receber'
import { Route as AuthenticatedFilialExtraRouteImport } from './routes/_authenticated/filial-extra'
import { Route as AuthenticatedFiscalRouteImport } from './routes/_authenticated/fiscal'
import { Route as AuthenticatedFluxoCaixaRouteImport } from './routes/_authenticated/fluxo-caixa'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedGiroEstoqueRouteImport } from './routes/_authenticated/giro-estoque'
import { Route as AuthenticatedImpostosRouteImport } from './routes/_authenticated/impostos'
import { Route as AuthenticatedImpostosFilialRouteImport } from './routes/_authenticated/impostos-filial'
import { Route as AuthenticatedImpostosNotaRouteImport } from './routes/_authenticated/impostos-nota'
import { Route as AuthenticatedInventariosRouteImport } from './routes/_authenticated/inventarios'
import { Route as AuthenticatedLucroRouteImport } from './routes/_authenticated/lucro'
import { Route as AuthenticatedMotoristaRouteImport } from './routes/_authenticated/motorista'
import { Route as AuthenticatedMotoristasRouteImport } from './routes/_authenticated/motoristas'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedNfeRouteImport } from './routes/_authenticated/nfe'
import { Route as AuthenticatedNfeEntradaRouteImport } from './routes/_authenticated/nfe-entrada'
import { Route as AuthenticatedObrasRouteImport } from './routes/_authenticated/obras'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedPainelFilialRouteImport } from './routes/_authenticated/painel-filial'
import { Route as AuthenticatedPainelFiscalRouteImport } from './routes/_authenticated/painel-fiscal'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPrecosRouteImport } from './routes/_authenticated/precos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated/profissionais'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedRelatorioComissoesRouteImport } from './routes/_authenticated/relatorio-comissoes'
import { Route as AuthenticatedRelatorioEstoqueRouteImport } from './routes/_authenticated/relatorio-estoque'
import { Route as AuthenticatedRotaRouteImport } from './routes/_authenticated/rota'
import { Route as AuthenticatedTransferenciasRouteImport } from './routes/_authenticated/transferencias'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedVendedoresRouteImport } from './routes/_authenticated/vendedores'
import { Route as AuthenticatedZeTechRouteImport } from './routes/_authenticated/ze-tech'
import { Route as AuthenticatedZeTechCobrancaRouteImport } from './routes/_authenticated/ze-tech-cobranca'
import { Route as AuthenticatedZeTechLojasRouteImport } from './routes/_authenticated/ze-tech-lojas'
import { Route as AuthenticatedZeTechNotasRouteImport } from './routes/_authenticated/ze-tech-notas'
import { Route as AuthenticatedZeTechPlanosRouteImport } from './routes/_authenticated/ze-tech-planos'
import { Route as AuthenticatedZeTechRelatoriosRouteImport } from './routes/_authenticated/ze-tech-relatorios'
import { Route as AuthenticatedComprasIndexRouteImport } from './routes/_authenticated/compras.index'
import { Route as AuthenticatedComprasIdRouteImport } from './routes/_authenticated/compras.$id'
import { Route as AuthenticatedDepositosIndexRouteImport } from './routes/_authenticated/depositos.index'
import { Route as AuthenticatedDepositosIdRouteImport } from './routes/_authenticated/depositos.$id'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeTechLoginRoute = ZeTechLoginRouteImport.update({
  id: '/ze-tech-login',
  path: '/ze-tech-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBalancoFiscalRoute =
  AuthenticatedBalancoFiscalRouteImport.update({
    id: '/balanco-fiscal',
    path: '/balanco-fiscal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBancoMovimentosRoute =
  AuthenticatedBancoMovimentosRouteImport.update({
    id: '/banco-movimentos',
    path: '/banco-movimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesObrasRoute =
  AuthenticatedClientesObrasRouteImport.update({
    id: '/clientes-obras',
    path: '/clientes-obras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasBancariasRoute =
  AuthenticatedContasBancariasRouteImport.update({
    id: '/contas-bancarias',
    path: '/contas-bancarias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasPagarRoute =
  AuthenticatedContasPagarRouteImport.update({
    id: '/contas-pagar',
    path: '/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasReceberRoute =
  AuthenticatedContasReceberRouteImport.update({
    id: '/contas-receber',
    path: '/contas-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCotacoesRoute = AuthenticatedCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditoRoute = AuthenticatedCreditoRouteImport.update({
  id: '/credito',
  path: '/credito',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueMovimentosRoute =
  AuthenticatedEstoqueMovimentosRouteImport.update({
    id: '/estoque-movimentos',
    path: '/estoque-movimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtratoReceberRoute =
  AuthenticatedExtratoReceberRouteImport.update({
    id: '/extrato-receber',
    path: '/extrato-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilialExtraRoute =
  AuthenticatedFilialExtraRouteImport.update({
    id: '/filial-extra',
    path: '/filial-extra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFiscalRoute = AuthenticatedFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluxoCaixaRoute = AuthenticatedFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGiroEstoqueRoute =
  AuthenticatedGiroEstoqueRouteImport.update({
    id: '/giro-estoque',
    path: '/giro-estoque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpostosRoute = AuthenticatedImpostosRouteImport.update({
  id: '/impostos',
  path: '/impostos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostosFilialRoute =
  AuthenticatedImpostosFilialRouteImport.update({
    id: '/impostos-filial',
    path: '/impostos-filial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpostosNotaRoute =
  AuthenticatedImpostosNotaRouteImport.update({
    id: '/impostos-nota',
    path: '/impostos-nota',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventariosRoute =
  AuthenticatedInventariosRouteImport.update({
    id: '/inventarios',
    path: '/inventarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLucroRoute = AuthenticatedLucroRouteImport.update({
  id: '/lucro',
  path: '/lucro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristaRoute = AuthenticatedMotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristasRoute = AuthenticatedMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNfeRoute = AuthenticatedNfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNfeEntradaRoute = AuthenticatedNfeEntradaRouteImport.update({
  id: '/nfe-entrada',
  path: '/nfe-entrada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasRoute = AuthenticatedObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelFilialRoute =
  AuthenticatedPainelFilialRouteImport.update({
    id: '/painel-filial',
    path: '/painel-filial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelFiscalRoute =
  AuthenticatedPainelFiscalRouteImport.update({
    id: '/painel-fiscal',
    path: '/painel-fiscal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecosRoute = AuthenticatedPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioComissoesRoute =
  AuthenticatedRelatorioComissoesRouteImport.update({
    id: '/relatorio-comissoes',
    path: '/relatorio-comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatorioEstoqueRoute =
  AuthenticatedRelatorioEstoqueRouteImport.update({
    id: '/relatorio-estoque',
    path: '/relatorio-estoque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaRoute = AuthenticatedRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransferenciasRoute =
  AuthenticatedTransferenciasRouteImport.update({
    id: '/transferencias',
    path: '/transferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedoresRoute = AuthenticatedVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZeTechRoute = AuthenticatedZeTechRouteImport.update({
  id: '/ze-tech',
  path: '/ze-tech',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZeTechCobrancaRoute =
  AuthenticatedZeTechCobrancaRouteImport.update({
    id: '/ze-tech-cobranca',
    path: '/ze-tech-cobranca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeTechLojasRoute =
  AuthenticatedZeTechLojasRouteImport.update({
    id: '/ze-tech-lojas',
    path: '/ze-tech-lojas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeTechNotasRoute =
  AuthenticatedZeTechNotasRouteImport.update({
    id: '/ze-tech-notas',
    path: '/ze-tech-notas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeTechPlanosRoute =
  AuthenticatedZeTechPlanosRouteImport.update({
    id: '/ze-tech-planos',
    path: '/ze-tech-planos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeTechRelatoriosRoute =
  AuthenticatedZeTechRelatoriosRouteImport.update({
    id: '/ze-tech-relatorios',
    path: '/ze-tech-relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasIndexRoute =
  AuthenticatedComprasIndexRouteImport.update({
    id: '/compras/',
    path: '/compras/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasIdRoute = AuthenticatedComprasIdRouteImport.update({
  id: '/compras/$id',
  path: '/compras/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositosIndexRoute =
  AuthenticatedDepositosIndexRouteImport.update({
    id: '/depositos/',
    path: '/depositos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositosIdRoute =
  AuthenticatedDepositosIdRouteImport.update({
    id: '/depositos/$id',
    path: '/depositos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/ze-tech-login': typeof ZeTechLoginRoute
  '/balanco-fiscal': typeof AuthenticatedBalancoFiscalRoute
  '/banco-movimentos': typeof AuthenticatedBancoMovimentosRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/clientes-obras': typeof AuthenticatedClientesObrasRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/cotacoes': typeof AuthenticatedCotacoesRoute
  '/credito': typeof AuthenticatedCreditoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/estoque-movimentos': typeof AuthenticatedEstoqueMovimentosRoute
  '/extrato-receber': typeof AuthenticatedExtratoReceberRoute
  '/filial-extra': typeof AuthenticatedFilialExtraRoute
  '/fiscal': typeof AuthenticatedFiscalRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/giro-estoque': typeof AuthenticatedGiroEstoqueRoute
  '/impostos': typeof AuthenticatedImpostosRoute
  '/impostos-filial': typeof AuthenticatedImpostosFilialRoute
  '/impostos-nota': typeof AuthenticatedImpostosNotaRoute
  '/inventarios': typeof AuthenticatedInventariosRoute
  '/lucro': typeof AuthenticatedLucroRoute
  '/motorista': typeof AuthenticatedMotoristaRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/nfe-entrada': typeof AuthenticatedNfeEntradaRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/painel-filial': typeof AuthenticatedPainelFilialRoute
  '/painel-fiscal': typeof AuthenticatedPainelFiscalRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/relatorio-comissoes': typeof AuthenticatedRelatorioComissoesRoute
  '/relatorio-estoque': typeof AuthenticatedRelatorioEstoqueRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/ze-tech': typeof AuthenticatedZeTechRoute
  '/ze-tech-cobranca': typeof AuthenticatedZeTechCobrancaRoute
  '/ze-tech-lojas': typeof AuthenticatedZeTechLojasRoute
  '/ze-tech-notas': typeof AuthenticatedZeTechNotasRoute
  '/ze-tech-planos': typeof AuthenticatedZeTechPlanosRoute
  '/ze-tech-relatorios': typeof AuthenticatedZeTechRelatoriosRoute
  '/compras/$id': typeof AuthenticatedComprasIdRoute
  '/depositos/$id': typeof AuthenticatedDepositosIdRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/compras/': typeof AuthenticatedComprasIndexRoute
  '/depositos/': typeof AuthenticatedDepositosIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/ze-tech-login': typeof ZeTechLoginRoute
  '/balanco-fiscal': typeof AuthenticatedBalancoFiscalRoute
  '/banco-movimentos': typeof AuthenticatedBancoMovimentosRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/clientes-obras': typeof AuthenticatedClientesObrasRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/cotacoes': typeof AuthenticatedCotacoesRoute
  '/credito': typeof AuthenticatedCreditoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/estoque-movimentos': typeof AuthenticatedEstoqueMovimentosRoute
  '/extrato-receber': typeof AuthenticatedExtratoReceberRoute
  '/filial-extra': typeof AuthenticatedFilialExtraRoute
  '/fiscal': typeof AuthenticatedFiscalRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/giro-estoque': typeof AuthenticatedGiroEstoqueRoute
  '/impostos': typeof AuthenticatedImpostosRoute
  '/impostos-filial': typeof AuthenticatedImpostosFilialRoute
  '/impostos-nota': typeof AuthenticatedImpostosNotaRoute
  '/inventarios': typeof AuthenticatedInventariosRoute
  '/lucro': typeof AuthenticatedLucroRoute
  '/motorista': typeof AuthenticatedMotoristaRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/nfe-entrada': typeof AuthenticatedNfeEntradaRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/painel-filial': typeof AuthenticatedPainelFilialRoute
  '/painel-fiscal': typeof AuthenticatedPainelFiscalRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/relatorio-comissoes': typeof AuthenticatedRelatorioComissoesRoute
  '/relatorio-estoque': typeof AuthenticatedRelatorioEstoqueRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/ze-tech': typeof AuthenticatedZeTechRoute
  '/ze-tech-cobranca': typeof AuthenticatedZeTechCobrancaRoute
  '/ze-tech-lojas': typeof AuthenticatedZeTechLojasRoute
  '/ze-tech-notas': typeof AuthenticatedZeTechNotasRoute
  '/ze-tech-planos': typeof AuthenticatedZeTechPlanosRoute
  '/ze-tech-relatorios': typeof AuthenticatedZeTechRelatoriosRoute
  '/compras/$id': typeof AuthenticatedComprasIdRoute
  '/depositos/$id': typeof AuthenticatedDepositosIdRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/compras': typeof AuthenticatedComprasIndexRoute
  '/depositos': typeof AuthenticatedDepositosIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/ze-tech-login': typeof ZeTechLoginRoute
  '/_authenticated/balanco-fiscal': typeof AuthenticatedBalancoFiscalRoute
  '/_authenticated/banco-movimentos': typeof AuthenticatedBancoMovimentosRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/clientes-obras': typeof AuthenticatedClientesObrasRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/_authenticated/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/_authenticated/contas-receber': typeof AuthenticatedContasReceberRoute
  '/_authenticated/cotacoes': typeof AuthenticatedCotacoesRoute
  '/_authenticated/credito': typeof AuthenticatedCreditoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/estoque-movimentos': typeof AuthenticatedEstoqueMovimentosRoute
  '/_authenticated/extrato-receber': typeof AuthenticatedExtratoReceberRoute
  '/_authenticated/filial-extra': typeof AuthenticatedFilialExtraRoute
  '/_authenticated/fiscal': typeof AuthenticatedFiscalRoute
  '/_authenticated/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/giro-estoque': typeof AuthenticatedGiroEstoqueRoute
  '/_authenticated/impostos': typeof AuthenticatedImpostosRoute
  '/_authenticated/impostos-filial': typeof AuthenticatedImpostosFilialRoute
  '/_authenticated/impostos-nota': typeof AuthenticatedImpostosNotaRoute
  '/_authenticated/inventarios': typeof AuthenticatedInventariosRoute
  '/_authenticated/lucro': typeof AuthenticatedLucroRoute
  '/_authenticated/motorista': typeof AuthenticatedMotoristaRoute
  '/_authenticated/motoristas': typeof AuthenticatedMotoristasRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/nfe': typeof AuthenticatedNfeRoute
  '/_authenticated/nfe-entrada': typeof AuthenticatedNfeEntradaRoute
  '/_authenticated/obras': typeof AuthenticatedObrasRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/painel-filial': typeof AuthenticatedPainelFilialRoute
  '/_authenticated/painel-fiscal': typeof AuthenticatedPainelFiscalRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/precos': typeof AuthenticatedPrecosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/relatorio-comissoes': typeof AuthenticatedRelatorioComissoesRoute
  '/_authenticated/relatorio-estoque': typeof AuthenticatedRelatorioEstoqueRoute
  '/_authenticated/rota': typeof AuthenticatedRotaRoute
  '/_authenticated/transferencias': typeof AuthenticatedTransferenciasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/_authenticated/vendedores': typeof AuthenticatedVendedoresRoute
  '/_authenticated/ze-tech': typeof AuthenticatedZeTechRoute
  '/_authenticated/ze-tech-cobranca': typeof AuthenticatedZeTechCobrancaRoute
  '/_authenticated/ze-tech-lojas': typeof AuthenticatedZeTechLojasRoute
  '/_authenticated/ze-tech-notas': typeof AuthenticatedZeTechNotasRoute
  '/_authenticated/ze-tech-planos': typeof AuthenticatedZeTechPlanosRoute
  '/_authenticated/ze-tech-relatorios': typeof AuthenticatedZeTechRelatoriosRoute
  '/_authenticated/compras/$id': typeof AuthenticatedComprasIdRoute
  '/_authenticated/depositos/$id': typeof AuthenticatedDepositosIdRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/compras/': typeof AuthenticatedComprasIndexRoute
  '/_authenticated/depositos/': typeof AuthenticatedDepositosIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/ze-tech-login'
    | '/balanco-fiscal'
    | '/banco-movimentos'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/clientes-obras'
    | '/comissoes'
    | '/configuracoes'
    | '/contas-bancarias'
    | '/contas-pagar'
    | '/contas-receber'
    | '/cotacoes'
    | '/credito'
    | '/dashboard'
    | '/empresa'
    | '/entregas'
    | '/estoque'
    | '/estoque-movimentos'
    | '/extrato-receber'
    | '/filial-extra'
    | '/fiscal'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/giro-estoque'
    | '/impostos'
    | '/impostos-filial'
    | '/impostos-nota'
    | '/inventarios'
    | '/lucro'
    | '/motorista'
    | '/motoristas'
    | '/movimentacoes'
    | '/nfe'
    | '/nfe-entrada'
    | '/obras'
    | '/orcamentos'
    | '/painel-filial'
    | '/painel-fiscal'
    | '/pdv'
    | '/planos'
    | '/precos'
    | '/produtos'
    | '/profissionais'
    | '/relatorio'
    | '/relatorio-comissoes'
    | '/relatorio-estoque'
    | '/rota'
    | '/transferencias'
    | '/usuarios'
    | '/veiculos'
    | '/vendedores'
    | '/ze-tech'
    | '/ze-tech-cobranca'
    | '/ze-tech-lojas'
    | '/ze-tech-notas'
    | '/ze-tech-planos'
    | '/ze-tech-relatorios'
    | '/compras/$id'
    | '/depositos/$id'
    | '/pedidos/$id'
    | '/compras/'
    | '/depositos/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/ze-tech-login'
    | '/balanco-fiscal'
    | '/banco-movimentos'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/clientes-obras'
    | '/comissoes'
    | '/configuracoes'
    | '/contas-bancarias'
    | '/contas-pagar'
    | '/contas-receber'
    | '/cotacoes'
    | '/credito'
    | '/dashboard'
    | '/empresa'
    | '/entregas'
    | '/estoque'
    | '/estoque-movimentos'
    | '/extrato-receber'
    | '/filial-extra'
    | '/fiscal'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/giro-estoque'
    | '/impostos'
    | '/impostos-filial'
    | '/impostos-nota'
    | '/inventarios'
    | '/lucro'
    | '/motorista'
    | '/motoristas'
    | '/movimentacoes'
    | '/nfe'
    | '/nfe-entrada'
    | '/obras'
    | '/orcamentos'
    | '/painel-filial'
    | '/painel-fiscal'
    | '/pdv'
    | '/planos'
    | '/precos'
    | '/produtos'
    | '/profissionais'
    | '/relatorio'
    | '/relatorio-comissoes'
    | '/relatorio-estoque'
    | '/rota'
    | '/transferencias'
    | '/usuarios'
    | '/veiculos'
    | '/vendedores'
    | '/ze-tech'
    | '/ze-tech-cobranca'
    | '/ze-tech-lojas'
    | '/ze-tech-notas'
    | '/ze-tech-planos'
    | '/ze-tech-relatorios'
    | '/compras/$id'
    | '/depositos/$id'
    | '/pedidos/$id'
    | '/compras'
    | '/depositos'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/ze-tech-login'
    | '/_authenticated/balanco-fiscal'
    | '/_authenticated/banco-movimentos'
    | '/_authenticated/caixa'
    | '/_authenticated/categorias'
    | '/_authenticated/clientes'
    | '/_authenticated/clientes-obras'
    | '/_authenticated/comissoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas-bancarias'
    | '/_authenticated/contas-pagar'
    | '/_authenticated/contas-receber'
    | '/_authenticated/cotacoes'
    | '/_authenticated/credito'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresa'
    | '/_authenticated/entregas'
    | '/_authenticated/estoque'
    | '/_authenticated/estoque-movimentos'
    | '/_authenticated/extrato-receber'
    | '/_authenticated/filial-extra'
    | '/_authenticated/fiscal'
    | '/_authenticated/fluxo-caixa'
    | '/_authenticated/fornecedores'
    | '/_authenticated/giro-estoque'
    | '/_authenticated/impostos'
    | '/_authenticated/impostos-filial'
    | '/_authenticated/impostos-nota'
    | '/_authenticated/inventarios'
    | '/_authenticated/lucro'
    | '/_authenticated/motorista'
    | '/_authenticated/motoristas'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/nfe'
    | '/_authenticated/nfe-entrada'
    | '/_authenticated/obras'
    | '/_authenticated/orcamentos'
    | '/_authenticated/painel-filial'
    | '/_authenticated/painel-fiscal'
    | '/_authenticated/pdv'
    | '/_authenticated/planos'
    | '/_authenticated/precos'
    | '/_authenticated/produtos'
    | '/_authenticated/profissionais'
    | '/_authenticated/relatorio'
    | '/_authenticated/relatorio-comissoes'
    | '/_authenticated/relatorio-estoque'
    | '/_authenticated/rota'
    | '/_authenticated/transferencias'
    | '/_authenticated/usuarios'
    | '/_authenticated/veiculos'
    | '/_authenticated/vendedores'
    | '/_authenticated/ze-tech'
    | '/_authenticated/ze-tech-cobranca'
    | '/_authenticated/ze-tech-lojas'
    | '/_authenticated/ze-tech-notas'
    | '/_authenticated/ze-tech-planos'
    | '/_authenticated/ze-tech-relatorios'
    | '/_authenticated/compras/$id'
    | '/_authenticated/depositos/$id'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/compras/'
    | '/_authenticated/depositos/'
    | '/_authenticated/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  ZeTechLoginRoute: typeof ZeTechLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ze-tech-login': {
      id: '/ze-tech-login'
      path: '/ze-tech-login'
      fullPath: '/ze-tech-login'
      preLoaderRoute: typeof ZeTechLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/balanco-fiscal': {
      id: '/_authenticated/balanco-fiscal'
      path: '/balanco-fiscal'
      fullPath: '/balanco-fiscal'
      preLoaderRoute: typeof AuthenticatedBalancoFiscalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banco-movimentos': {
      id: '/_authenticated/banco-movimentos'
      path: '/banco-movimentos'
      fullPath: '/banco-movimentos'
      preLoaderRoute: typeof AuthenticatedBancoMovimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes-obras': {
      id: '/_authenticated/clientes-obras'
      path: '/clientes-obras'
      fullPath: '/clientes-obras'
      preLoaderRoute: typeof AuthenticatedClientesObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-bancarias': {
      id: '/_authenticated/contas-bancarias'
      path: '/contas-bancarias'
      fullPath: '/contas-bancarias'
      preLoaderRoute: typeof AuthenticatedContasBancariasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-pagar': {
      id: '/_authenticated/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/contas-pagar'
      preLoaderRoute: typeof AuthenticatedContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-receber': {
      id: '/_authenticated/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AuthenticatedContasReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes': {
      id: '/_authenticated/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof AuthenticatedCotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credito': {
      id: '/_authenticated/credito'
      path: '/credito'
      fullPath: '/credito'
      preLoaderRoute: typeof AuthenticatedCreditoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque-movimentos': {
      id: '/_authenticated/estoque-movimentos'
      path: '/estoque-movimentos'
      fullPath: '/estoque-movimentos'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extrato-receber': {
      id: '/_authenticated/extrato-receber'
      path: '/extrato-receber'
      fullPath: '/extrato-receber'
      preLoaderRoute: typeof AuthenticatedExtratoReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filial-extra': {
      id: '/_authenticated/filial-extra'
      path: '/filial-extra'
      fullPath: '/filial-extra'
      preLoaderRoute: typeof AuthenticatedFilialExtraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiscal': {
      id: '/_authenticated/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof AuthenticatedFiscalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo-caixa': {
      id: '/_authenticated/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/giro-estoque': {
      id: '/_authenticated/giro-estoque'
      path: '/giro-estoque'
      fullPath: '/giro-estoque'
      preLoaderRoute: typeof AuthenticatedGiroEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostos': {
      id: '/_authenticated/impostos'
      path: '/impostos'
      fullPath: '/impostos'
      preLoaderRoute: typeof AuthenticatedImpostosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostos-filial': {
      id: '/_authenticated/impostos-filial'
      path: '/impostos-filial'
      fullPath: '/impostos-filial'
      preLoaderRoute: typeof AuthenticatedImpostosFilialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostos-nota': {
      id: '/_authenticated/impostos-nota'
      path: '/impostos-nota'
      fullPath: '/impostos-nota'
      preLoaderRoute: typeof AuthenticatedImpostosNotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventarios': {
      id: '/_authenticated/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof AuthenticatedInventariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lucro': {
      id: '/_authenticated/lucro'
      path: '/lucro'
      fullPath: '/lucro'
      preLoaderRoute: typeof AuthenticatedLucroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorista': {
      id: '/_authenticated/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof AuthenticatedMotoristaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motoristas': {
      id: '/_authenticated/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof AuthenticatedMotoristasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfe': {
      id: '/_authenticated/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof AuthenticatedNfeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfe-entrada': {
      id: '/_authenticated/nfe-entrada'
      path: '/nfe-entrada'
      fullPath: '/nfe-entrada'
      preLoaderRoute: typeof AuthenticatedNfeEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras': {
      id: '/_authenticated/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AuthenticatedObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-filial': {
      id: '/_authenticated/painel-filial'
      path: '/painel-filial'
      fullPath: '/painel-filial'
      preLoaderRoute: typeof AuthenticatedPainelFilialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-fiscal': {
      id: '/_authenticated/painel-fiscal'
      path: '/painel-fiscal'
      fullPath: '/painel-fiscal'
      preLoaderRoute: typeof AuthenticatedPainelFiscalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precos': {
      id: '/_authenticated/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof AuthenticatedPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio-comissoes': {
      id: '/_authenticated/relatorio-comissoes'
      path: '/relatorio-comissoes'
      fullPath: '/relatorio-comissoes'
      preLoaderRoute: typeof AuthenticatedRelatorioComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio-estoque': {
      id: '/_authenticated/relatorio-estoque'
      path: '/relatorio-estoque'
      fullPath: '/relatorio-estoque'
      preLoaderRoute: typeof AuthenticatedRelatorioEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota': {
      id: '/_authenticated/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AuthenticatedRotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transferencias': {
      id: '/_authenticated/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof AuthenticatedTransferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedores': {
      id: '/_authenticated/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AuthenticatedVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ze-tech': {
      id: '/_authenticated/ze-tech'
      path: '/ze-tech'
      fullPath: '/ze-tech'
      preLoaderRoute: typeof AuthenticatedZeTechRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ze-tech-cobranca': {
      id: '/_authenticated/ze-tech-cobranca'
      path: '/ze-tech-cobranca'
      fullPath: '/ze-tech-cobranca'
      preLoaderRoute: typeof AuthenticatedZeTechCobrancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ze-tech-lojas': {
      id: '/_authenticated/ze-tech-lojas'
      path: '/ze-tech-lojas'
      fullPath: '/ze-tech-lojas'
      preLoaderRoute: typeof AuthenticatedZeTechLojasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ze-tech-notas': {
      id: '/_authenticated/ze-tech-notas'
      path: '/ze-tech-notas'
      fullPath: '/ze-tech-notas'
      preLoaderRoute: typeof AuthenticatedZeTechNotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ze-tech-planos': {
      id: '/_authenticated/ze-tech-planos'
      path: '/ze-tech-planos'
      fullPath: '/ze-tech-planos'
      preLoaderRoute: typeof AuthenticatedZeTechPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ze-tech-relatorios': {
      id: '/_authenticated/ze-tech-relatorios'
      path: '/ze-tech-relatorios'
      fullPath: '/ze-tech-relatorios'
      preLoaderRoute: typeof AuthenticatedZeTechRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras/': {
      id: '/_authenticated/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof AuthenticatedComprasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras/$id': {
      id: '/_authenticated/compras/$id'
      path: '/compras/$id'
      fullPath: '/compras/$id'
      preLoaderRoute: typeof AuthenticatedComprasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depositos/': {
      id: '/_authenticated/depositos/'
      path: '/depositos'
      fullPath: '/depositos/'
      preLoaderRoute: typeof AuthenticatedDepositosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depositos/$id': {
      id: '/_authenticated/depositos/$id'
      path: '/depositos/$id'
      fullPath: '/depositos/$id'
      preLoaderRoute: typeof AuthenticatedDepositosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBalancoFiscalRoute: typeof AuthenticatedBalancoFiscalRoute
  AuthenticatedBancoMovimentosRoute: typeof AuthenticatedBancoMovimentosRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedClientesObrasRoute: typeof AuthenticatedClientesObrasRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasBancariasRoute: typeof AuthenticatedContasBancariasRoute
  AuthenticatedContasPagarRoute: typeof AuthenticatedContasPagarRoute
  AuthenticatedContasReceberRoute: typeof AuthenticatedContasReceberRoute
  AuthenticatedCotacoesRoute: typeof AuthenticatedCotacoesRoute
  AuthenticatedCreditoRoute: typeof AuthenticatedCreditoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedEstoqueMovimentosRoute: typeof AuthenticatedEstoqueMovimentosRoute
  AuthenticatedExtratoReceberRoute: typeof AuthenticatedExtratoReceberRoute
  AuthenticatedFilialExtraRoute: typeof AuthenticatedFilialExtraRoute
  AuthenticatedFiscalRoute: typeof AuthenticatedFiscalRoute
  AuthenticatedFluxoCaixaRoute: typeof AuthenticatedFluxoCaixaRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedGiroEstoqueRoute: typeof AuthenticatedGiroEstoqueRoute
  AuthenticatedImpostosRoute: typeof AuthenticatedImpostosRoute
  AuthenticatedImpostosFilialRoute: typeof AuthenticatedImpostosFilialRoute
  AuthenticatedImpostosNotaRoute: typeof AuthenticatedImpostosNotaRoute
  AuthenticatedInventariosRoute: typeof AuthenticatedInventariosRoute
  AuthenticatedLucroRoute: typeof AuthenticatedLucroRoute
  AuthenticatedMotoristaRoute: typeof AuthenticatedMotoristaRoute
  AuthenticatedMotoristasRoute: typeof AuthenticatedMotoristasRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedNfeRoute: typeof AuthenticatedNfeRoute
  AuthenticatedNfeEntradaRoute: typeof AuthenticatedNfeEntradaRoute
  AuthenticatedObrasRoute: typeof AuthenticatedObrasRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPainelFilialRoute: typeof AuthenticatedPainelFilialRoute
  AuthenticatedPainelFiscalRoute: typeof AuthenticatedPainelFiscalRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPrecosRoute: typeof AuthenticatedPrecosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedRelatorioComissoesRoute: typeof AuthenticatedRelatorioComissoesRoute
  AuthenticatedRelatorioEstoqueRoute: typeof AuthenticatedRelatorioEstoqueRoute
  AuthenticatedRotaRoute: typeof AuthenticatedRotaRoute
  AuthenticatedTransferenciasRoute: typeof AuthenticatedTransferenciasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedVendedoresRoute: typeof AuthenticatedVendedoresRoute
  AuthenticatedZeTechRoute: typeof AuthenticatedZeTechRoute
  AuthenticatedZeTechCobrancaRoute: typeof AuthenticatedZeTechCobrancaRoute
  AuthenticatedZeTechLojasRoute: typeof AuthenticatedZeTechLojasRoute
  AuthenticatedZeTechNotasRoute: typeof AuthenticatedZeTechNotasRoute
  AuthenticatedZeTechPlanosRoute: typeof AuthenticatedZeTechPlanosRoute
  AuthenticatedZeTechRelatoriosRoute: typeof AuthenticatedZeTechRelatoriosRoute
  AuthenticatedComprasIdRoute: typeof AuthenticatedComprasIdRoute
  AuthenticatedDepositosIdRoute: typeof AuthenticatedDepositosIdRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedComprasIndexRoute: typeof AuthenticatedComprasIndexRoute
  AuthenticatedDepositosIndexRoute: typeof AuthenticatedDepositosIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBalancoFiscalRoute: AuthenticatedBalancoFiscalRoute,
  AuthenticatedBancoMovimentosRoute: AuthenticatedBancoMovimentosRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedClientesObrasRoute: AuthenticatedClientesObrasRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContasBancariasRoute: AuthenticatedContasBancariasRoute,
  AuthenticatedContasPagarRoute: AuthenticatedContasPagarRoute,
  AuthenticatedContasReceberRoute: AuthenticatedContasReceberRoute,
  AuthenticatedCotacoesRoute: AuthenticatedCotacoesRoute,
  AuthenticatedCreditoRoute: AuthenticatedCreditoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedEstoqueMovimentosRoute: AuthenticatedEstoqueMovimentosRoute,
  AuthenticatedExtratoReceberRoute: AuthenticatedExtratoReceberRoute,
  AuthenticatedFilialExtraRoute: AuthenticatedFilialExtraRoute,
  AuthenticatedFiscalRoute: AuthenticatedFiscalRoute,
  AuthenticatedFluxoCaixaRoute: AuthenticatedFluxoCaixaRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedGiroEstoqueRoute: AuthenticatedGiroEstoqueRoute,
  AuthenticatedImpostosRoute: AuthenticatedImpostosRoute,
  AuthenticatedImpostosFilialRoute: AuthenticatedImpostosFilialRoute,
  AuthenticatedImpostosNotaRoute: AuthenticatedImpostosNotaRoute,
  AuthenticatedInventariosRoute: AuthenticatedInventariosRoute,
  AuthenticatedLucroRoute: AuthenticatedLucroRoute,
  AuthenticatedMotoristaRoute: AuthenticatedMotoristaRoute,
  AuthenticatedMotoristasRoute: AuthenticatedMotoristasRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedNfeRoute: AuthenticatedNfeRoute,
  AuthenticatedNfeEntradaRoute: AuthenticatedNfeEntradaRoute,
  AuthenticatedObrasRoute: AuthenticatedObrasRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPainelFilialRoute: AuthenticatedPainelFilialRoute,
  AuthenticatedPainelFiscalRoute: AuthenticatedPainelFiscalRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPrecosRoute: AuthenticatedPrecosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedRelatorioComissoesRoute: AuthenticatedRelatorioComissoesRoute,
  AuthenticatedRelatorioEstoqueRoute: AuthenticatedRelatorioEstoqueRoute,
  AuthenticatedRotaRoute: AuthenticatedRotaRoute,
  AuthenticatedTransferenciasRoute: AuthenticatedTransferenciasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedVendedoresRoute: AuthenticatedVendedoresRoute,
  AuthenticatedZeTechRoute: AuthenticatedZeTechRoute,
  AuthenticatedZeTechCobrancaRoute: AuthenticatedZeTechCobrancaRoute,
  AuthenticatedZeTechLojasRoute: AuthenticatedZeTechLojasRoute,
  AuthenticatedZeTechNotasRoute: AuthenticatedZeTechNotasRoute,
  AuthenticatedZeTechPlanosRoute: AuthenticatedZeTechPlanosRoute,
  AuthenticatedZeTechRelatoriosRoute: AuthenticatedZeTechRelatoriosRoute,
  AuthenticatedComprasIdRoute: AuthenticatedComprasIdRoute,
  AuthenticatedDepositosIdRoute: AuthenticatedDepositosIdRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedComprasIndexRoute: AuthenticatedComprasIndexRoute,
  AuthenticatedDepositosIndexRoute: AuthenticatedDepositosIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  ZeTechLoginRoute: ZeTechLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
